//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace InaportClientBJTI.StaggingPelindo3 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="inaportserviceSoap", Namespace="http://src/")]
    public partial class inaportservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetPkkByCabangSubsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRkbmByPkkSubsOperationCompleted;
        
        private System.Threading.SendOrPostCallback entryRpkRoSubsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setStatusRkbmSubsOperationCompleted;
        
        private System.Threading.SendOrPostCallback entryLogDokumenOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public inaportservice() {
            this.Url = global::InaportClientBJTI.Properties.Settings.Default.InaportClientBJTI_StaggingPelindo3_inaportservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPkkByCabangSubsCompletedEventHandler GetPkkByCabangSubsCompleted;
        
        /// <remarks/>
        public event GetRkbmByPkkSubsCompletedEventHandler GetRkbmByPkkSubsCompleted;
        
        /// <remarks/>
        public event entryRpkRoSubsCompletedEventHandler entryRpkRoSubsCompleted;
        
        /// <remarks/>
        public event setStatusRkbmSubsCompletedEventHandler setStatusRkbmSubsCompleted;
        
        /// <remarks/>
        public event entryLogDokumenCompletedEventHandler entryLogDokumenCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://src/GetPkkByCabangSubs", RequestNamespace="http://src/", ResponseNamespace="http://src/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public pkk[] GetPkkByCabangSubs(string kd_cabang) {
            object[] results = this.Invoke("GetPkkByCabangSubs", new object[] {
                        kd_cabang});
            return ((pkk[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPkkByCabangSubsAsync(string kd_cabang) {
            this.GetPkkByCabangSubsAsync(kd_cabang, null);
        }
        
        /// <remarks/>
        public void GetPkkByCabangSubsAsync(string kd_cabang, object userState) {
            if ((this.GetPkkByCabangSubsOperationCompleted == null)) {
                this.GetPkkByCabangSubsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPkkByCabangSubsOperationCompleted);
            }
            this.InvokeAsync("GetPkkByCabangSubs", new object[] {
                        kd_cabang}, this.GetPkkByCabangSubsOperationCompleted, userState);
        }
        
        private void OnGetPkkByCabangSubsOperationCompleted(object arg) {
            if ((this.GetPkkByCabangSubsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPkkByCabangSubsCompleted(this, new GetPkkByCabangSubsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://src/GetRkbmByPkkSubs", RequestNamespace="http://src/", ResponseNamespace="http://src/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public rkbm[] GetRkbmByPkkSubs(string nomor_pkk) {
            object[] results = this.Invoke("GetRkbmByPkkSubs", new object[] {
                        nomor_pkk});
            return ((rkbm[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRkbmByPkkSubsAsync(string nomor_pkk) {
            this.GetRkbmByPkkSubsAsync(nomor_pkk, null);
        }
        
        /// <remarks/>
        public void GetRkbmByPkkSubsAsync(string nomor_pkk, object userState) {
            if ((this.GetRkbmByPkkSubsOperationCompleted == null)) {
                this.GetRkbmByPkkSubsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRkbmByPkkSubsOperationCompleted);
            }
            this.InvokeAsync("GetRkbmByPkkSubs", new object[] {
                        nomor_pkk}, this.GetRkbmByPkkSubsOperationCompleted, userState);
        }
        
        private void OnGetRkbmByPkkSubsOperationCompleted(object arg) {
            if ((this.GetRkbmByPkkSubsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRkbmByPkkSubsCompleted(this, new GetRkbmByPkkSubsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://src/entryRpkRoSubs", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Namespace="http://src/")]
        public _return entryRpkRoSubs([System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] rpkro req) {
            object[] results = this.Invoke("entryRpkRoSubs", new object[] {
                        req});
            return ((_return)(results[0]));
        }
        
        /// <remarks/>
        public void entryRpkRoSubsAsync(rpkro req) {
            this.entryRpkRoSubsAsync(req, null);
        }
        
        /// <remarks/>
        public void entryRpkRoSubsAsync(rpkro req, object userState) {
            if ((this.entryRpkRoSubsOperationCompleted == null)) {
                this.entryRpkRoSubsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnentryRpkRoSubsOperationCompleted);
            }
            this.InvokeAsync("entryRpkRoSubs", new object[] {
                        req}, this.entryRpkRoSubsOperationCompleted, userState);
        }
        
        private void OnentryRpkRoSubsOperationCompleted(object arg) {
            if ((this.entryRpkRoSubsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.entryRpkRoSubsCompleted(this, new entryRpkRoSubsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://src/setStatusRkbmSubs", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")]
        public _return setStatusRkbmSubs([System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string nomorRkbmMuat, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string nomorRkbmBongkar, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string idTos) {
            object[] results = this.Invoke("setStatusRkbmSubs", new object[] {
                        nomorRkbmMuat,
                        nomorRkbmBongkar,
                        idTos});
            return ((_return)(results[0]));
        }
        
        /// <remarks/>
        public void setStatusRkbmSubsAsync(string nomorRkbmMuat, string nomorRkbmBongkar, string idTos) {
            this.setStatusRkbmSubsAsync(nomorRkbmMuat, nomorRkbmBongkar, idTos, null);
        }
        
        /// <remarks/>
        public void setStatusRkbmSubsAsync(string nomorRkbmMuat, string nomorRkbmBongkar, string idTos, object userState) {
            if ((this.setStatusRkbmSubsOperationCompleted == null)) {
                this.setStatusRkbmSubsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetStatusRkbmSubsOperationCompleted);
            }
            this.InvokeAsync("setStatusRkbmSubs", new object[] {
                        nomorRkbmMuat,
                        nomorRkbmBongkar,
                        idTos}, this.setStatusRkbmSubsOperationCompleted, userState);
        }
        
        private void OnsetStatusRkbmSubsOperationCompleted(object arg) {
            if ((this.setStatusRkbmSubsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setStatusRkbmSubsCompleted(this, new setStatusRkbmSubsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://src/entryLogDokumen", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")]
        public _return entryLogDokumen([System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string nomorPkk, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string id_desk, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string vmodul, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string vmodul_path, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string param1, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string param2, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string param3, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string paramdate1, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string paramdate2, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://src/")] string paramdate3) {
            object[] results = this.Invoke("entryLogDokumen", new object[] {
                        nomorPkk,
                        id_desk,
                        vmodul,
                        vmodul_path,
                        param1,
                        param2,
                        param3,
                        paramdate1,
                        paramdate2,
                        paramdate3});
            return ((_return)(results[0]));
        }
        
        /// <remarks/>
        public void entryLogDokumenAsync(string nomorPkk, string id_desk, string vmodul, string vmodul_path, string param1, string param2, string param3, string paramdate1, string paramdate2, string paramdate3) {
            this.entryLogDokumenAsync(nomorPkk, id_desk, vmodul, vmodul_path, param1, param2, param3, paramdate1, paramdate2, paramdate3, null);
        }
        
        /// <remarks/>
        public void entryLogDokumenAsync(string nomorPkk, string id_desk, string vmodul, string vmodul_path, string param1, string param2, string param3, string paramdate1, string paramdate2, string paramdate3, object userState) {
            if ((this.entryLogDokumenOperationCompleted == null)) {
                this.entryLogDokumenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnentryLogDokumenOperationCompleted);
            }
            this.InvokeAsync("entryLogDokumen", new object[] {
                        nomorPkk,
                        id_desk,
                        vmodul,
                        vmodul_path,
                        param1,
                        param2,
                        param3,
                        paramdate1,
                        paramdate2,
                        paramdate3}, this.entryLogDokumenOperationCompleted, userState);
        }
        
        private void OnentryLogDokumenOperationCompleted(object arg) {
            if ((this.entryLogDokumenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.entryLogDokumenCompleted(this, new entryLogDokumenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://src/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src/")]
    public partial class ResponseMessagePkk {
        
        private string nomorRkbmMuatField;
        
        private string nomorRkbmBongkarField;
        
        private string nomorPKKField;
        
        private string nomorRpkRoField;
        
        private string nomorPpkField;
        
        private string nomorPpkbField;
        
        private string nomorSpkField;
        
        private string nomorSpogField;
        
        private string portCodeField;
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        /// <remarks/>
        public string nomorRkbmMuat {
            get {
                return this.nomorRkbmMuatField;
            }
            set {
                this.nomorRkbmMuatField = value;
            }
        }
        
        /// <remarks/>
        public string nomorRkbmBongkar {
            get {
                return this.nomorRkbmBongkarField;
            }
            set {
                this.nomorRkbmBongkarField = value;
            }
        }
        
        /// <remarks/>
        public string nomorPKK {
            get {
                return this.nomorPKKField;
            }
            set {
                this.nomorPKKField = value;
            }
        }
        
        /// <remarks/>
        public string nomorRpkRo {
            get {
                return this.nomorRpkRoField;
            }
            set {
                this.nomorRpkRoField = value;
            }
        }
        
        /// <remarks/>
        public string nomorPpk {
            get {
                return this.nomorPpkField;
            }
            set {
                this.nomorPpkField = value;
            }
        }
        
        /// <remarks/>
        public string nomorPpkb {
            get {
                return this.nomorPpkbField;
            }
            set {
                this.nomorPpkbField = value;
            }
        }
        
        /// <remarks/>
        public string nomorSpk {
            get {
                return this.nomorSpkField;
            }
            set {
                this.nomorSpkField = value;
            }
        }
        
        /// <remarks/>
        public string nomorSpog {
            get {
                return this.nomorSpogField;
            }
            set {
                this.nomorSpogField = value;
            }
        }
        
        /// <remarks/>
        public string portCode {
            get {
                return this.portCodeField;
            }
            set {
                this.portCodeField = value;
            }
        }
        
        /// <remarks/>
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src/")]
    public partial class _return {
        
        private ResponseMessagePkk returnField;
        
        /// <remarks/>
        public ResponseMessagePkk @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src/")]
    public partial class rpkro {
        
        private string kodeDermagaField;
        
        private string tanggalRencanaField;
        
        private string nomorRpkRoField;
        
        private string nomorPkkField;
        
        private string nomorRkbmMuatField;
        
        private string nomorRkbmBongkarField;
        
        private string kegiatanBongkarField;
        
        private string kegiatanMuatField;
        
        private string komoditiField;
        
        private string nomorGudangField;
        
        private string keteranganField;
        
        private string tanggalMulaiTambatField;
        
        private string jamSelesaiTambatField;
        
        private string tanggalSelesaiTambatField;
        
        private string jamMulaiTambatField;
        
        private string kadeMeterAwalField;
        
        private string kadeMeterAkhirField;
        
        private string statusField;
        
        private string portCodeField;
        
        /// <remarks/>
        public string kodeDermaga {
            get {
                return this.kodeDermagaField;
            }
            set {
                this.kodeDermagaField = value;
            }
        }
        
        /// <remarks/>
        public string tanggalRencana {
            get {
                return this.tanggalRencanaField;
            }
            set {
                this.tanggalRencanaField = value;
            }
        }
        
        /// <remarks/>
        public string nomorRpkRo {
            get {
                return this.nomorRpkRoField;
            }
            set {
                this.nomorRpkRoField = value;
            }
        }
        
        /// <remarks/>
        public string nomorPkk {
            get {
                return this.nomorPkkField;
            }
            set {
                this.nomorPkkField = value;
            }
        }
        
        /// <remarks/>
        public string nomorRkbmMuat {
            get {
                return this.nomorRkbmMuatField;
            }
            set {
                this.nomorRkbmMuatField = value;
            }
        }
        
        /// <remarks/>
        public string nomorRkbmBongkar {
            get {
                return this.nomorRkbmBongkarField;
            }
            set {
                this.nomorRkbmBongkarField = value;
            }
        }
        
        /// <remarks/>
        public string kegiatanBongkar {
            get {
                return this.kegiatanBongkarField;
            }
            set {
                this.kegiatanBongkarField = value;
            }
        }
        
        /// <remarks/>
        public string kegiatanMuat {
            get {
                return this.kegiatanMuatField;
            }
            set {
                this.kegiatanMuatField = value;
            }
        }
        
        /// <remarks/>
        public string komoditi {
            get {
                return this.komoditiField;
            }
            set {
                this.komoditiField = value;
            }
        }
        
        /// <remarks/>
        public string nomorGudang {
            get {
                return this.nomorGudangField;
            }
            set {
                this.nomorGudangField = value;
            }
        }
        
        /// <remarks/>
        public string keterangan {
            get {
                return this.keteranganField;
            }
            set {
                this.keteranganField = value;
            }
        }
        
        /// <remarks/>
        public string tanggalMulaiTambat {
            get {
                return this.tanggalMulaiTambatField;
            }
            set {
                this.tanggalMulaiTambatField = value;
            }
        }
        
        /// <remarks/>
        public string jamSelesaiTambat {
            get {
                return this.jamSelesaiTambatField;
            }
            set {
                this.jamSelesaiTambatField = value;
            }
        }
        
        /// <remarks/>
        public string tanggalSelesaiTambat {
            get {
                return this.tanggalSelesaiTambatField;
            }
            set {
                this.tanggalSelesaiTambatField = value;
            }
        }
        
        /// <remarks/>
        public string jamMulaiTambat {
            get {
                return this.jamMulaiTambatField;
            }
            set {
                this.jamMulaiTambatField = value;
            }
        }
        
        /// <remarks/>
        public string kadeMeterAwal {
            get {
                return this.kadeMeterAwalField;
            }
            set {
                this.kadeMeterAwalField = value;
            }
        }
        
        /// <remarks/>
        public string kadeMeterAkhir {
            get {
                return this.kadeMeterAkhirField;
            }
            set {
                this.kadeMeterAkhirField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string portCode {
            get {
                return this.portCodeField;
            }
            set {
                this.portCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src/")]
    public partial class rkbm {
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        private string nOMOR_PKKField;
        
        private string nAMA_BARANGField;
        
        private string bAHAYAField;
        
        private string gANGGUField;
        
        private string kEGIATANField;
        
        private string uNITField;
        
        private string tONField;
        
        private string m3Field;
        
        private string pENYALURANField;
        
        private string kADEField;
        
        private string pBMField;
        
        private string nPWP_PBMField;
        
        private string cONSIGNEEField;
        
        private string sHIPPERField;
        
        private string nPWP_SHIPPERField;
        
        private string bLNOField;
        
        private string gANGField;
        
        private string pALKAField;
        
        private string kODE_PELABUHANField;
        
        private string nAMA_PELABUHANField;
        
        private string nO_RKBM_MUATField;
        
        private string nO_RKBM_BONGKARField;
        
        private string kD_CABANGField;
        
        /// <remarks/>
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        public string NOMOR_PKK {
            get {
                return this.nOMOR_PKKField;
            }
            set {
                this.nOMOR_PKKField = value;
            }
        }
        
        /// <remarks/>
        public string NAMA_BARANG {
            get {
                return this.nAMA_BARANGField;
            }
            set {
                this.nAMA_BARANGField = value;
            }
        }
        
        /// <remarks/>
        public string BAHAYA {
            get {
                return this.bAHAYAField;
            }
            set {
                this.bAHAYAField = value;
            }
        }
        
        /// <remarks/>
        public string GANGGU {
            get {
                return this.gANGGUField;
            }
            set {
                this.gANGGUField = value;
            }
        }
        
        /// <remarks/>
        public string KEGIATAN {
            get {
                return this.kEGIATANField;
            }
            set {
                this.kEGIATANField = value;
            }
        }
        
        /// <remarks/>
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        public string TON {
            get {
                return this.tONField;
            }
            set {
                this.tONField = value;
            }
        }
        
        /// <remarks/>
        public string M3 {
            get {
                return this.m3Field;
            }
            set {
                this.m3Field = value;
            }
        }
        
        /// <remarks/>
        public string PENYALURAN {
            get {
                return this.pENYALURANField;
            }
            set {
                this.pENYALURANField = value;
            }
        }
        
        /// <remarks/>
        public string KADE {
            get {
                return this.kADEField;
            }
            set {
                this.kADEField = value;
            }
        }
        
        /// <remarks/>
        public string PBM {
            get {
                return this.pBMField;
            }
            set {
                this.pBMField = value;
            }
        }
        
        /// <remarks/>
        public string NPWP_PBM {
            get {
                return this.nPWP_PBMField;
            }
            set {
                this.nPWP_PBMField = value;
            }
        }
        
        /// <remarks/>
        public string CONSIGNEE {
            get {
                return this.cONSIGNEEField;
            }
            set {
                this.cONSIGNEEField = value;
            }
        }
        
        /// <remarks/>
        public string SHIPPER {
            get {
                return this.sHIPPERField;
            }
            set {
                this.sHIPPERField = value;
            }
        }
        
        /// <remarks/>
        public string NPWP_SHIPPER {
            get {
                return this.nPWP_SHIPPERField;
            }
            set {
                this.nPWP_SHIPPERField = value;
            }
        }
        
        /// <remarks/>
        public string BLNO {
            get {
                return this.bLNOField;
            }
            set {
                this.bLNOField = value;
            }
        }
        
        /// <remarks/>
        public string GANG {
            get {
                return this.gANGField;
            }
            set {
                this.gANGField = value;
            }
        }
        
        /// <remarks/>
        public string PALKA {
            get {
                return this.pALKAField;
            }
            set {
                this.pALKAField = value;
            }
        }
        
        /// <remarks/>
        public string KODE_PELABUHAN {
            get {
                return this.kODE_PELABUHANField;
            }
            set {
                this.kODE_PELABUHANField = value;
            }
        }
        
        /// <remarks/>
        public string NAMA_PELABUHAN {
            get {
                return this.nAMA_PELABUHANField;
            }
            set {
                this.nAMA_PELABUHANField = value;
            }
        }
        
        /// <remarks/>
        public string NO_RKBM_MUAT {
            get {
                return this.nO_RKBM_MUATField;
            }
            set {
                this.nO_RKBM_MUATField = value;
            }
        }
        
        /// <remarks/>
        public string NO_RKBM_BONGKAR {
            get {
                return this.nO_RKBM_BONGKARField;
            }
            set {
                this.nO_RKBM_BONGKARField = value;
            }
        }
        
        /// <remarks/>
        public string KD_CABANG {
            get {
                return this.kD_CABANGField;
            }
            set {
                this.kD_CABANGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src/")]
    public partial class pkk {
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        private string nO_PPKB1AField;
        
        private string nOMOR_PKKField;
        
        private string nAKHODAField;
        
        private string kODE_KAPALField;
        
        private string tANDA_PENDAFTARAN_KAPALField;
        
        private string nAMA_KAPALField;
        
        private string bENDERAField;
        
        private string nAMA_BENDERAField;
        
        private string dRTField;
        
        private string gRTField;
        
        private string lOAField;
        
        private string dRMAXField;
        
        private string dRDEPANField;
        
        private string dRBELAKANGField;
        
        private string dRTENGAHField;
        
        private string cALL_SIGNField;
        
        private string iMO_NUMBERField;
        
        private string kODE_PEL_ASALField;
        
        private string nAMA_PEL_ASALField;
        
        private string kODE_PEL_TUJUANField;
        
        private string nAMA_PEL_TUJUANField;
        
        private string tANGGAL_ETAField;
        
        private string jAM_ETAField;
        
        private string tANGGAL_ETDField;
        
        private string jAM_ETDField;
        
        private string jENIS_BARANGField;
        
        private string jENIS_KAPALField;
        
        private string jENIS_BARANG_LAINField;
        
        private string jENIS_BARANG_LAIN_BField;
        
        private string jENIS_BARANG_LAIN_MField;
        
        private string aGEN_PELAYARANField;
        
        private string dERMAGAField;
        
        private string pENUMPANG_NAIK_TURUN_BONGKARField;
        
        private string pENUMPANG_NAIK_TURUN_MUATField;
        
        private string cONTAINER_BONGKAR_ISI_40Field;
        
        private string cONTAINER_BONGKAR_ISI_20Field;
        
        private string cONTAINER_BONGKAR_ISI_40_EMPTYField;
        
        private string cONTAINER_BONGKAR_ISI_20_EMPTYField;
        
        private string cONTAINER_MUAT_ISI_40Field;
        
        private string cONTAINER_MUAT_ISI_20Field;
        
        private string cONTAINER_MUAT_ISI_40_EMPTYField;
        
        private string cONTAINER_MUAT_ISI_20_EMPTYField;
        
        private string cARGO_BARANG_CAMPUR_BONGKARField;
        
        private string cARGO_BARANG_CAMPUR_MUATField;
        
        private string cARGO_BARANG_KARUNG_BONGKARField;
        
        private string cARGO_BARANG_KARUNG_MUATField;
        
        private string cARGO_BARANG_CURAH_BONGKARField;
        
        private string cARGO_BARANG_CURAH_MUATField;
        
        private string cARGO_BARANG_CAIR_BONGKARField;
        
        private string cARGO_BARANG_CAIR_MUATField;
        
        private string cARGO_BARANG_BERBAHAYA_BONGKARField;
        
        private string cARGO_BARANG_BERBAHAYA_MUATField;
        
        private string jUMLAH_BONGKARField;
        
        private string jUMLAH_MUATField;
        
        private string hEWAN_NAIK_TURUN_BONGKARField;
        
        private string hEWAN_NAIK_TURUN_MUATField;
        
        private string cREATED_DATEField;
        
        private string pORTCODEField;
        
        /// <remarks/>
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        public string NO_PPKB1A {
            get {
                return this.nO_PPKB1AField;
            }
            set {
                this.nO_PPKB1AField = value;
            }
        }
        
        /// <remarks/>
        public string NOMOR_PKK {
            get {
                return this.nOMOR_PKKField;
            }
            set {
                this.nOMOR_PKKField = value;
            }
        }
        
        /// <remarks/>
        public string NAKHODA {
            get {
                return this.nAKHODAField;
            }
            set {
                this.nAKHODAField = value;
            }
        }
        
        /// <remarks/>
        public string KODE_KAPAL {
            get {
                return this.kODE_KAPALField;
            }
            set {
                this.kODE_KAPALField = value;
            }
        }
        
        /// <remarks/>
        public string TANDA_PENDAFTARAN_KAPAL {
            get {
                return this.tANDA_PENDAFTARAN_KAPALField;
            }
            set {
                this.tANDA_PENDAFTARAN_KAPALField = value;
            }
        }
        
        /// <remarks/>
        public string NAMA_KAPAL {
            get {
                return this.nAMA_KAPALField;
            }
            set {
                this.nAMA_KAPALField = value;
            }
        }
        
        /// <remarks/>
        public string BENDERA {
            get {
                return this.bENDERAField;
            }
            set {
                this.bENDERAField = value;
            }
        }
        
        /// <remarks/>
        public string NAMA_BENDERA {
            get {
                return this.nAMA_BENDERAField;
            }
            set {
                this.nAMA_BENDERAField = value;
            }
        }
        
        /// <remarks/>
        public string DRT {
            get {
                return this.dRTField;
            }
            set {
                this.dRTField = value;
            }
        }
        
        /// <remarks/>
        public string GRT {
            get {
                return this.gRTField;
            }
            set {
                this.gRTField = value;
            }
        }
        
        /// <remarks/>
        public string LOA {
            get {
                return this.lOAField;
            }
            set {
                this.lOAField = value;
            }
        }
        
        /// <remarks/>
        public string DRMAX {
            get {
                return this.dRMAXField;
            }
            set {
                this.dRMAXField = value;
            }
        }
        
        /// <remarks/>
        public string DRDEPAN {
            get {
                return this.dRDEPANField;
            }
            set {
                this.dRDEPANField = value;
            }
        }
        
        /// <remarks/>
        public string DRBELAKANG {
            get {
                return this.dRBELAKANGField;
            }
            set {
                this.dRBELAKANGField = value;
            }
        }
        
        /// <remarks/>
        public string DRTENGAH {
            get {
                return this.dRTENGAHField;
            }
            set {
                this.dRTENGAHField = value;
            }
        }
        
        /// <remarks/>
        public string CALL_SIGN {
            get {
                return this.cALL_SIGNField;
            }
            set {
                this.cALL_SIGNField = value;
            }
        }
        
        /// <remarks/>
        public string IMO_NUMBER {
            get {
                return this.iMO_NUMBERField;
            }
            set {
                this.iMO_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        public string KODE_PEL_ASAL {
            get {
                return this.kODE_PEL_ASALField;
            }
            set {
                this.kODE_PEL_ASALField = value;
            }
        }
        
        /// <remarks/>
        public string NAMA_PEL_ASAL {
            get {
                return this.nAMA_PEL_ASALField;
            }
            set {
                this.nAMA_PEL_ASALField = value;
            }
        }
        
        /// <remarks/>
        public string KODE_PEL_TUJUAN {
            get {
                return this.kODE_PEL_TUJUANField;
            }
            set {
                this.kODE_PEL_TUJUANField = value;
            }
        }
        
        /// <remarks/>
        public string NAMA_PEL_TUJUAN {
            get {
                return this.nAMA_PEL_TUJUANField;
            }
            set {
                this.nAMA_PEL_TUJUANField = value;
            }
        }
        
        /// <remarks/>
        public string TANGGAL_ETA {
            get {
                return this.tANGGAL_ETAField;
            }
            set {
                this.tANGGAL_ETAField = value;
            }
        }
        
        /// <remarks/>
        public string JAM_ETA {
            get {
                return this.jAM_ETAField;
            }
            set {
                this.jAM_ETAField = value;
            }
        }
        
        /// <remarks/>
        public string TANGGAL_ETD {
            get {
                return this.tANGGAL_ETDField;
            }
            set {
                this.tANGGAL_ETDField = value;
            }
        }
        
        /// <remarks/>
        public string JAM_ETD {
            get {
                return this.jAM_ETDField;
            }
            set {
                this.jAM_ETDField = value;
            }
        }
        
        /// <remarks/>
        public string JENIS_BARANG {
            get {
                return this.jENIS_BARANGField;
            }
            set {
                this.jENIS_BARANGField = value;
            }
        }
        
        /// <remarks/>
        public string JENIS_KAPAL {
            get {
                return this.jENIS_KAPALField;
            }
            set {
                this.jENIS_KAPALField = value;
            }
        }
        
        /// <remarks/>
        public string JENIS_BARANG_LAIN {
            get {
                return this.jENIS_BARANG_LAINField;
            }
            set {
                this.jENIS_BARANG_LAINField = value;
            }
        }
        
        /// <remarks/>
        public string JENIS_BARANG_LAIN_B {
            get {
                return this.jENIS_BARANG_LAIN_BField;
            }
            set {
                this.jENIS_BARANG_LAIN_BField = value;
            }
        }
        
        /// <remarks/>
        public string JENIS_BARANG_LAIN_M {
            get {
                return this.jENIS_BARANG_LAIN_MField;
            }
            set {
                this.jENIS_BARANG_LAIN_MField = value;
            }
        }
        
        /// <remarks/>
        public string AGEN_PELAYARAN {
            get {
                return this.aGEN_PELAYARANField;
            }
            set {
                this.aGEN_PELAYARANField = value;
            }
        }
        
        /// <remarks/>
        public string DERMAGA {
            get {
                return this.dERMAGAField;
            }
            set {
                this.dERMAGAField = value;
            }
        }
        
        /// <remarks/>
        public string PENUMPANG_NAIK_TURUN_BONGKAR {
            get {
                return this.pENUMPANG_NAIK_TURUN_BONGKARField;
            }
            set {
                this.pENUMPANG_NAIK_TURUN_BONGKARField = value;
            }
        }
        
        /// <remarks/>
        public string PENUMPANG_NAIK_TURUN_MUAT {
            get {
                return this.pENUMPANG_NAIK_TURUN_MUATField;
            }
            set {
                this.pENUMPANG_NAIK_TURUN_MUATField = value;
            }
        }
        
        /// <remarks/>
        public string CONTAINER_BONGKAR_ISI_40 {
            get {
                return this.cONTAINER_BONGKAR_ISI_40Field;
            }
            set {
                this.cONTAINER_BONGKAR_ISI_40Field = value;
            }
        }
        
        /// <remarks/>
        public string CONTAINER_BONGKAR_ISI_20 {
            get {
                return this.cONTAINER_BONGKAR_ISI_20Field;
            }
            set {
                this.cONTAINER_BONGKAR_ISI_20Field = value;
            }
        }
        
        /// <remarks/>
        public string CONTAINER_BONGKAR_ISI_40_EMPTY {
            get {
                return this.cONTAINER_BONGKAR_ISI_40_EMPTYField;
            }
            set {
                this.cONTAINER_BONGKAR_ISI_40_EMPTYField = value;
            }
        }
        
        /// <remarks/>
        public string CONTAINER_BONGKAR_ISI_20_EMPTY {
            get {
                return this.cONTAINER_BONGKAR_ISI_20_EMPTYField;
            }
            set {
                this.cONTAINER_BONGKAR_ISI_20_EMPTYField = value;
            }
        }
        
        /// <remarks/>
        public string CONTAINER_MUAT_ISI_40 {
            get {
                return this.cONTAINER_MUAT_ISI_40Field;
            }
            set {
                this.cONTAINER_MUAT_ISI_40Field = value;
            }
        }
        
        /// <remarks/>
        public string CONTAINER_MUAT_ISI_20 {
            get {
                return this.cONTAINER_MUAT_ISI_20Field;
            }
            set {
                this.cONTAINER_MUAT_ISI_20Field = value;
            }
        }
        
        /// <remarks/>
        public string CONTAINER_MUAT_ISI_40_EMPTY {
            get {
                return this.cONTAINER_MUAT_ISI_40_EMPTYField;
            }
            set {
                this.cONTAINER_MUAT_ISI_40_EMPTYField = value;
            }
        }
        
        /// <remarks/>
        public string CONTAINER_MUAT_ISI_20_EMPTY {
            get {
                return this.cONTAINER_MUAT_ISI_20_EMPTYField;
            }
            set {
                this.cONTAINER_MUAT_ISI_20_EMPTYField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_CAMPUR_BONGKAR {
            get {
                return this.cARGO_BARANG_CAMPUR_BONGKARField;
            }
            set {
                this.cARGO_BARANG_CAMPUR_BONGKARField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_CAMPUR_MUAT {
            get {
                return this.cARGO_BARANG_CAMPUR_MUATField;
            }
            set {
                this.cARGO_BARANG_CAMPUR_MUATField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_KARUNG_BONGKAR {
            get {
                return this.cARGO_BARANG_KARUNG_BONGKARField;
            }
            set {
                this.cARGO_BARANG_KARUNG_BONGKARField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_KARUNG_MUAT {
            get {
                return this.cARGO_BARANG_KARUNG_MUATField;
            }
            set {
                this.cARGO_BARANG_KARUNG_MUATField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_CURAH_BONGKAR {
            get {
                return this.cARGO_BARANG_CURAH_BONGKARField;
            }
            set {
                this.cARGO_BARANG_CURAH_BONGKARField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_CURAH_MUAT {
            get {
                return this.cARGO_BARANG_CURAH_MUATField;
            }
            set {
                this.cARGO_BARANG_CURAH_MUATField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_CAIR_BONGKAR {
            get {
                return this.cARGO_BARANG_CAIR_BONGKARField;
            }
            set {
                this.cARGO_BARANG_CAIR_BONGKARField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_CAIR_MUAT {
            get {
                return this.cARGO_BARANG_CAIR_MUATField;
            }
            set {
                this.cARGO_BARANG_CAIR_MUATField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_BERBAHAYA_BONGKAR {
            get {
                return this.cARGO_BARANG_BERBAHAYA_BONGKARField;
            }
            set {
                this.cARGO_BARANG_BERBAHAYA_BONGKARField = value;
            }
        }
        
        /// <remarks/>
        public string CARGO_BARANG_BERBAHAYA_MUAT {
            get {
                return this.cARGO_BARANG_BERBAHAYA_MUATField;
            }
            set {
                this.cARGO_BARANG_BERBAHAYA_MUATField = value;
            }
        }
        
        /// <remarks/>
        public string JUMLAH_BONGKAR {
            get {
                return this.jUMLAH_BONGKARField;
            }
            set {
                this.jUMLAH_BONGKARField = value;
            }
        }
        
        /// <remarks/>
        public string JUMLAH_MUAT {
            get {
                return this.jUMLAH_MUATField;
            }
            set {
                this.jUMLAH_MUATField = value;
            }
        }
        
        /// <remarks/>
        public string HEWAN_NAIK_TURUN_BONGKAR {
            get {
                return this.hEWAN_NAIK_TURUN_BONGKARField;
            }
            set {
                this.hEWAN_NAIK_TURUN_BONGKARField = value;
            }
        }
        
        /// <remarks/>
        public string HEWAN_NAIK_TURUN_MUAT {
            get {
                return this.hEWAN_NAIK_TURUN_MUATField;
            }
            set {
                this.hEWAN_NAIK_TURUN_MUATField = value;
            }
        }
        
        /// <remarks/>
        public string CREATED_DATE {
            get {
                return this.cREATED_DATEField;
            }
            set {
                this.cREATED_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string PORTCODE {
            get {
                return this.pORTCODEField;
            }
            set {
                this.pORTCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetPkkByCabangSubsCompletedEventHandler(object sender, GetPkkByCabangSubsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPkkByCabangSubsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPkkByCabangSubsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public pkk[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((pkk[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetRkbmByPkkSubsCompletedEventHandler(object sender, GetRkbmByPkkSubsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRkbmByPkkSubsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRkbmByPkkSubsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public rkbm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((rkbm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void entryRpkRoSubsCompletedEventHandler(object sender, entryRpkRoSubsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class entryRpkRoSubsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal entryRpkRoSubsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_return)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void setStatusRkbmSubsCompletedEventHandler(object sender, setStatusRkbmSubsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setStatusRkbmSubsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setStatusRkbmSubsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_return)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void entryLogDokumenCompletedEventHandler(object sender, entryLogDokumenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class entryLogDokumenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal entryLogDokumenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _return Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_return)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591